project_path: dp_cars
project_name: dp_cars
project_description: Cars data product
branch_name: us001
branch_description: User story 1
readme_general_note: Data product to explore cars stopping distance
board_params_set_dried: board_params_set_local(board_alias = "cars_test", folder =
  "~/devel/test")
creds_set_dried: ~
